Gosrock/Ticket-Backend-22nd

- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.interface.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dtos/RegisterUser.request.dto.ts
- src/auth/dtos/RegisterUser.response.dto.ts
- src/auth/dtos/ValidateNumber.response.dto.ts
- src/auth/guards/AccessToken.guard.ts
- src/auth/guards/RegisterToken.guard.ts
- src/auth/guards/jwt.guard.ts
- src/common/decorators/registerUser.decorator.ts
- src/common/decorators/roles.decorator.ts
- src/common/decorators/user.decorator.ts
- src/common/exceptions/http-exception.filter.ts
- src/common/funcs/getConnectedRepository.ts
- src/common/interceptors/sucess.interceptor.ts
- src/common/utils/swagger.ts
- src/database/entities/user.entity.ts
- src/database/repositories/user.repository.ts
- src/users/users.controller.spec.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- src/users/users.service.ts
보일러 플레이트 완료
dev 브런치
보일러 플레이트 관련 내용 작업
#1
> 🚀  보일러 플레이트 완료

- .github/workflows/docker-publish.yml
> :rocket: feat(ci): docker images name 설정

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
> :hammer: fix(auth) : 파일명 대소문자 수정

- src/common/errors/ValidtionError.ts
:hammer: fix(error) : 검증오류 응답값 개선
> :hammer: fix(error) : 검증오류 응답값 개선

- src/auth/auth.service.ts
- src/auth/guards/AccessToken.guard.ts
어스 가드부분 유저 서비스 의존성 제거
fix/auth-accessGuard
어스 가드에서 유저 서비스 의존성을 제거했습니다.
> :hammer: fix(accessguard) : 어스 가드부분 유저 서비스 의존성 제거

- src/database/repositories/ticket.repository.ts
티켓 모듈 트랜잭션 적용
feature/ticket
updateStatus 트랜잭션
#39 티켓 모듈 트랜잭션
> :hammer: feat(ticket): updateStatus 트랜잭션 적용#39

- src/database/repositories/ticket.repository.ts
- src/tickets/tickets.service.ts
티켓 트랜잭션 수정
refactor/ticket
서비스 로직으로 이동
#39
> :hammer: fix(ticket) 티켓 트랜잭션 서비스 로직으로 이동#39

- src/auth/auth.service.ts
- src/slack/dtos/SlackNewOrder.dto.ts
- src/slack/dtos/SlackOrderStateChange.dto.ts
- src/slack/dtos/SlackTicketQREnterEvent.dto.ts
- src/slack/dtos/SlackTicketStateChange.dto.ts
- src/slack/dtos/SlackValidationNumberDM.dto.ts
- src/slack/dtos/index.ts
- src/slack/slack.service.spec.ts
- src/slack/slack.service.ts
- src/slack/slackFake.service.ts
슬랙 알림 모듈 관련해서 인자를 dto로 리팩토링
refactor/slack-dto
리팩토링 이슈
#43 
이전 슬랙 알림 모듈 함수  메시지큐에서 필요한 함수 나열 항목
#26
> 슬랙 알림 모듈 관련해서 인자를 dto로 리팩토링

- src/slack/slackFake.service.ts
:hammer: fix(slack) : 슬랙 fake 서비스에 로거 추가 (#49)
refactor/slackFake-service-log
#49
> :hammer: fix(slack) : 슬랙 fake 서비스에 로거 추가 (#49)

- src/socket/socket-admin.gateway.ts
- src/socket/socket.service.ts
- src/tickets/dtos/update-ticket-status.dto.ts
- src/tickets/tickets.service.ts
emitToAll 메서드 추가해서 코드 간소화
refector/socket
SocketService 에서 emitToAll 메서드 추가
TicketService 에서 emitToAll 메서드 사용
#51
> :hammer: fix(socket): SocketService 메서드 간소화 (#51)

- src/orders/orders.service.ts
티켓생성 한번에 비동기요청 하도록 리펙토링
feature/order
#42
> :hammer: fix(order): 티켓생성 한번에 비동기요청 리펙토링#42

- package-lock.json
- package.json
- src/common/pipes/orderId-validation.pipe.ts
- src/database/repositories/order.repository.ts
- src/database/repositories/ticket.repository.ts
- src/orders/orders.controller.ts
- src/orders/orders.service.ts
- src/tickets/tickets.service.ts
주문 모듈:
유저 id로 해당 유저의 모든 주문목록 조회,
주문 id로 해당 주문에 속한 티켓조회 (현재 기획에 없음)
feature/order
#55
> :rocket: feat(order): 유저 주문목록 조회, 주문별 티켓목록 조회 #55

- package-lock.json
- src/common/consts/enum.ts
- src/queue/queue.consumer.sms.ts
- src/queue/queue.module.ts
- src/queue/queue.service.ts
- src/sms/sms.service.ts
* 티켓 생성 시 발송되는 문자의 형식을 맞추고 순서를 보장 하는 로직을 추가했습니다.
refactor/queueMessageContent
#65
> 🔨 refactor(queue): 문자 형식 변경 및 순서 보장 로직 추가 

- package-lock.json
- src/database/repositories/order.repository.ts
- src/orders/dtos/request-order.dto.ts
- src/orders/dtos/response-order.dto.ts
- src/orders/dtos/response-orderlist.dto.ts
- src/orders/orders.controller.ts
- src/orders/orders.service.ts
- src/queue/queue.service.ts
주문생성시 Response 실응답과 swagger예시 맞춤
Response Dto로 수정
Feature/order 
#42
> Feature/order 주문생성시 Response 실응답과 swagger예시 맞춤

- src/tickets/tickets.controller.ts
Ticket 의 user가 null인 에러 해결
fix/ticket
빠져있던 ReqUser 추가하였습니다
실수했네요
#73
> :hammer: fix(ticket) /ticket/create 유저가 null 인 에러 해결 #73

- src/app.controller.ts
- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/guards/AccessToken.guard.ts
- src/auth/guards/RegisterToken.guard.ts
- src/common/decorators/ErrorResponse.decorator.ts
- src/common/decorators/SuccessResponse.decorator.ts
- src/common/decorators/registerUser.decorator.ts
- src/common/decorators/returnValueToDto.decorator.ts
- src/common/decorators/user.decorator.ts
- src/common/dtos/SuccessCommonResponse.dto.ts
- src/common/exceptions/http-exception.filter.ts
- src/common/funcs/toKRTimezone.ts
- src/common/interceptors/sucess.interceptor.ts
- src/common/utils/makeInstanceByApiProperty.ts
- src/common/utils/mergeTwoObj.ts
- src/database/migrations/typeOrm.config.ts
- src/database/repositories/ticket.repository.ts
- src/database/repositories/user.repository.spec.ts
- src/database/repositories/user.repository.ts
- src/queue/queue.consumer.sms.ts
- src/queue/queue.consumer.ts
- src/queue/queue.service.ts
- src/redis/redis.service.ts
- src/slack/slack.service.spec.ts
- src/slack/slack.service.ts
- src/socket/socket.service.ts
- src/tickets/tickets.controller.ts
에러 응답 데코레이터와 비슷하게 여러 예시를 추가할수 있는 데코레이터를 만들었습니다
주요 기능
-  커스텀하고싶은 응답값을 수정할수있습니다. overwriteValue 기능 제공
- Dto class에 apiProperty 로 기술하였던 descriptipn 부분을 가져와서 객체로 만듭니다.
- 만들어진 객체로 응답 예시값을 제작합니다. 이때 overwriteValue 을 사용해서 커스텀 할수있습니다.
- 같은 상태코드여도 여러 예시를 보여줄수있습니다.
- 원래코드
- https://github.com/Gosrock/Ticket-Backend-22th/blob/e123f449dcfa405a5a9bec01c032123f799ae594/src/auth/auth.controller.ts#L88-L111
```javascript
@ApiResponse({
description:
'최초회원가입 한 유저면 registerToken을 , 이후 로그인 한 사람이면 accessToken을 발급합니다.',
content: {
'application/json': {
schema: {
oneOf: [
{ $ref: getSchemaPath(FirstReigsterDto) },
{ $ref: getSchemaPath(LoginResponseDto) }
]
},
examples: {
'최초 (회원가입 안한 유저일때 )': {
value: makeInstanceByApiProperty(FirstReigsterDto),
description:
'리턴된 registerToken을 Bearer <registerToken> 형식으로 …
```
> 🚀 스웨거 같은 상태코드 여러예시 데코레이터 추가

- src/app.controller.ts
- src/auth/Errors/AuthErrorDefine.ts
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/guards/AccessToken.guard.ts
- src/auth/guards/TrottlerBehindProxy.guard.ts
- src/common/decorators/ErrorResponse.decorator.ts
- src/common/errors/ErrorDefine.kr.ts
- src/common/errors/HttpExceptionError.response.dto.ts
- src/common/errors/ValidationError.response.dto.ts
- src/common/errors/ValidtionError.ts
- src/common/exceptions/http-exception.filter.ts
- src/tickets/tickets.controller.ts
에러 코드가 필요할것 같아서 에러 목록을 정리했습니다
refactor/error-code
#81
> Refactor/error code 인증모듈 에러 정의

- src/common/utils/makeInstanceByApiProperty.ts
- src/database/entities/order.entity.ts
- src/tickets/tickets.controller.ts
> :hammer: fix(util) : 어레이형 타입 꺼내오기로 수정

- src/orders/dtos/report.dto.ts
- src/orders/orders.controller.ts
- src/orders/orders.service.ts
- src/tickets/tickets.controller.ts
주문모듈 전체 수정사항 반영
feature/order
#93
> :hammer: refactor(order): 전체 수정사항 반영 #93

- src/database/repositories/comment.repository.ts
- src/users/dtos/Scroll/ScrollMeta.dto.ts
- src/users/dtos/Scroll/ScrollOptions.dto.ts
- src/users/users.service.spec.ts
댓글 스크롤 기능 수정
feature/user
댓글 스크롤 기능 수정 및 dto 수정
> 🔨refactor(user) : 댓글 스크롤 조회 기능 수정 #91

- src/orders/orders.service.ts
- src/queue/queue.consumer.sms.ts
- src/queue/queue.consumer.ts
- src/queue/queue.service.ts
* 주문 상태가 관리자에 의해 변경 될 시 슬랙 알림을 보내는 메서드를 비동기적으로 큐를 통해 호출하는 기능 추가
* 메시지 포맷 변경
feature/orderStatusUpdateQueue
#101
> 🚀 : feat(queue): 주문 상태 변경 시, 슬랙 알림 기능 추가 및 메시지 포맷 변경 

- src/database/repositories/order.repository.ts
- src/orders/dtos/order-find.dto.ts
관리자 페이지네이션에서 공짜티켓여부 False일때 조회가 안됨
응답에 user 가 형식이 맞지 않음
feature/order
#103
> Feature/order 주문모듈 : 관리자 페이지네이션 조회 버그수정

- src/users/users.controller.ts
> [v0.1.6] 댓글모듈 재배포

- src/database/repositories/user.repository.ts
- src/users/dtos/Comment.response.dto.ts
- src/users/dtos/UserFind.dto.ts
- src/users/dtos/UserTicketNum.response.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
유저 조회 변경 내용 수정
feature/user
어드민용 유저 조회 검색 기능(입금자명, 전화번호) 추가
가입일자 넣어주기(createAt)
댓글 유저정보 나오지 않도록 수정
> Feature/user 유저 조회

- src/auth/auth.service.ts
- src/queue/queue.consumer.ts
- src/queue/queue.service.ts
- src/tickets/tickets.service.ts
티켓 상태 변경을 입장과 그 외 나머지로 나누어서 큐에 다른 키로 넣는 작업을 진행했습니다.
feature/ticketStatusUpdateQueue
#113
> :rocket: feat(queue): 티켓 상태 변경 따로 빼서 작업 

- src/tickets/tickets.controller.ts
- src/tickets/tickets.service.ts
스웨거 티켓 입장 응답 예시 추가
feature/ticket
스웨거용 응답 예시 추가
#118
> :hammer: refactor(ticket): 티켓 입장 응답 예시 추가 #118

- src/auth/dtos/AdminSendValidationNumber.response.dto.ts
- src/auth/dtos/RequestValidation.response.dto.ts
> :hammer: fix(auth) : 테스트 기간 인증번호 추가

- src/auth/auth.interface.ts
- src/auth/auth.service.ts
- src/auth/guards/AccessToken.guard.ts
- src/common/decorators/user.decorator.ts
- src/database/entities/user.entity.ts
- src/database/repositories/user.repository.ts
- src/tickets/tickets.controller.ts
- src/tickets/tickets.service.ts
- src/users/users.service.ts
> [v1.0.3] user eager option false로 ... 쿼리 속도저하 개선

- src/tickets/tickets.controller.ts
> :hammer: fix(ticket) : 타입 관련 수정

- src/database/repositories/comment.repository.ts
- src/users/dtos/Comment.response.dto.ts
- src/users/dtos/CommentNum.response.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
feature/user
응원 댓글 개수 조회 api 구현
> 응원 댓글 개수 조회 api 구현

- src/database/repositories/comment.repository.ts
- src/tickets/tickets.controller.ts
- src/users/dtos/Comment.response.dto.ts
- src/users/dtos/CommentNum.response.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
> [v1.0.4] 응원 댓글 개수 조회 api 구현

- src/database/repositories/comment.repository.ts
- src/users/dtos/RandomCommentUser.response.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
feature/user
유저 정보 포함한 랜덤 댓글 뽑기 기능 구현
> feat(user) : 랜덤 댓글 뽑기 기능(유저 정보 포함)

- src/auth/auth.controller.ts
- src/auth/dtos/AdminSendValidationNumber.response.dto.ts
- src/auth/dtos/RequestValidation.response.dto.ts
- src/common/utils/makeInstanceByApiProperty.ts
- src/database/repositories/comment.repository.ts
- src/orders/orders.controller.ts
- src/users/users.controller.ts
> [v1.0.7] 프로덕션 대비 ,인증번호 응답값, 로그 주석처리

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/dtos/Login.response.dto.ts
- src/auth/dtos/RequestValidation.response.dto.ts
- src/auth/guards/AccessToken.guard.ts
- src/common/decorators/SuccessResponse.decorator.ts
- src/database/repositories/user.repository.ts
- src/orders/orders.controller.ts
> [v1.0.8] 폰인증번호 expose , 어세스토큰 관련 로직수정

- README.md
- src/auth/dtos/RequestValidation.response.dto.ts
> [v1.1.0] 프로덕션 대비

- src/auth/auth.service.ts
- src/auth/dtos/RequestValidation.response.dto.ts
> [v1.1.1] 인증토큰 만료시간변화
